// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://github.com/bextract"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tier1/fetch": {
            "post": {
                "description": "Performs a plain HTTP GET (or fetches an API endpoint directly)\nusing a rotating User-Agent pool. No JavaScript execution.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tier1"
                ],
                "summary": "Tier 1 static HTTP fetch",
                "parameters": [
                    {
                        "description": "Fetch parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tier1handler.FetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tier1handler.FetchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/tier1handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/tier1handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "tier1handler.ErrorResponse": {
            "description": "Error detail returned on failure.",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "dial tcp: connection refused"
                }
            }
        },
        "tier1handler.FetchRequest": {
            "description": "Target URL and optional overrides for the Tier 1 static fetch.",
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "api_endpoint": {
                    "type": "string",
                    "example": "https://api.example.com/data"
                },
                "timeout_ms": {
                    "type": "integer",
                    "example": 5000
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "tier1handler.FetchResponse": {
            "description": "Raw HTTP response metadata and body returned by Tier 1.",
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "\u003chtml\u003e...\u003c/html\u003e"
                },
                "body_size": {
                    "type": "integer",
                    "example": 14823
                },
                "content_type": {
                    "type": "string",
                    "example": "text/html"
                },
                "elapsed_ms": {
                    "type": "integer",
                    "example": 342
                },
                "final_url": {
                    "type": "string",
                    "example": "https://example.com/"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "bextract API",
	Description:      "Multi-tier web data extraction pipeline. Tier 1 performs plain static HTTP fetches.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
