// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://github.com/bextract"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/extract": {
            "post": {
                "description": "Fetches the URL and cascades through Tier 1 → Tier 2 → Tier 3 → Tier 4, stopping at the first non-Escalate decision.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "extract"
                ],
                "summary": "Full extraction cascade",
                "parameters": [
                    {
                        "description": "Extraction parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ExtractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ExtractResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "description": "Error detail returned on failure.",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "dial tcp: connection refused"
                }
            }
        },
        "api.ExtractRequest": {
            "description": "URL and optional per-request timeout overrides for the full extraction cascade.",
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "api_endpoint": {
                    "type": "string",
                    "example": "https://api.example.com/product/123"
                },
                "extraction_timeout_ms": {
                    "type": "integer",
                    "example": 5000
                },
                "fetch_timeout_ms": {
                    "type": "integer",
                    "example": 10000
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/product/123"
                }
            }
        },
        "api.ExtractResponse": {
            "description": "Extract result including which tier produced the final result, the decision, page type, and extracted fields.",
            "type": "object",
            "properties": {
                "decision": {
                    "type": "string",
                    "example": "Done"
                },
                "elapsed_ms": {
                    "type": "integer",
                    "example": 320
                },
                "escalation_reason": {
                    "type": "string",
                    "example": ""
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/api.FieldResponse"
                    }
                },
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "page_type": {
                    "type": "string",
                    "example": "content-rich"
                },
                "tier": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "api.FieldResponse": {
            "description": "A data field extracted from the page.",
            "type": "object",
            "properties": {
                "source": {
                    "type": "string",
                    "example": "json-ld"
                },
                "value": {
                    "type": "string",
                    "example": "29.99"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "bextract API",
	Description:      "Multi-tier web data extraction pipeline. Tier 1 performs plain static HTTP fetches.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
